### ISSUE TITLE
`ksp-cfg-mode` forces a reindent whenever called for the first time

### ISSUE THREAD

**Issue by jgkamat** [lashtear/ksp-cfg-mode#1]
When running `ksp-cfg-mode` in a buffer, an indentation is forced, which dosen't happen for other modes. I'm not sure what's causing this at first glance though, but for large craft files this is quite an issue (as the indenation takes ~30 seconds).

Let me know if you can't reproduce this, and I'll try to find out if this is an issue specific to my config.

Nice job by the way! :smile:

**Comment by lashtear** [comment]
There are two problems there; one-- that indentation and whitespace cleanup is forced, and two that it is slow for large files.

I'll make the indentation configurable and default-off.

30 seconds to re-indent is terrible, yes; the current system has an O(n^2) problem, but I didn't have any .cfg files on-hand that were large enough for that to be a concern.  Easy enough to implement an O(n) indent-region, which will fix that.

Should have a fix for both of these later today.

**Comment by jgkamat** [comment]
Thanks! It's not such a problem that the indentation takes a while, but rather that it forces indentation/white-space cleanup whenever the mode is enabled. This will solve my issue, thanks!

**Comment by lashtear** [comment]
0069a0bc implements making that configurable; I'll tag a new release once I've got the rest of it fixed.

**Comment by jgkamat** [comment]
Thanks so much, everything is working fine now!
